name: Copy multiple Docker Image
run-name: Copy Docker Images
on:
  workflow_dispatch:
    inputs:
      source_1:
        description: '第一个镜像源 (Registry)'
        required: true
        default: 'docker.io'
      destination_1:
        description: '第一个目标源 (Registry)'
        required: true
        default: 'registry.cn-shenzhen.aliyuncs.com'
      source_repo_1:
        description: '第一个源仓库及标签 (格式 repo:tag)'
        required: true
        default: 'nginx:1.21.1'
      destination_repo_1:
        description: '第一个目标仓库及标签 (格式 repo:tag)'
        required: true
        default: 'dockerproxy_cc/nginx:1.21.1'
      source_2:
        description: '第二个镜像源 (Registry)'
        required: false
        default: ''
      source_repo_2:
        description: '第二个源仓库及标签 (格式 repo:tag)'
        required: false
        default: ''
      destination_repo_2:
        description: '第二个目标仓库及标签 (格式 repo:tag)'
        required: false
        default: ''

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Docker Image from source 1
        uses: ikrong/docker-sync-action@main
        with:
          source: ${{ github.event.inputs.source_1 }}
          source-credential: ${{ secrets.SOURCE_CREDENTIAL }}
          destination: ${{ github.event.inputs.destination }}
          destination-credential: ${{ secrets.DESTINATION_CREDENTIAL }}
          copy: "${{ github.event.inputs.source_repo_1 }} ${{ github.event.inputs.destination_repo_1 }}"

      - name: Copy Docker Image from source 2
        if: ${{ github.event.inputs.source_2 != '' && github.event.inputs.source_repo_2 != '' && github.event.inputs.destination_repo_2 != '' }}
        uses: ikrong/docker-sync-action@main
        with:
          source: ${{ github.event.inputs.source_2 }}
          source-credential: ${{ secrets.SOURCE_CREDENTIAL }}
          destination: ${{ github.event.inputs.destination }}
          destination-credential: ${{ secrets.DESTINATION_CREDENTIAL }}
          copy: "${{ github.event.inputs.source_repo_1 }} ${{ github.event.inputs.destination_repo_1 }}"
